config/routes.rb
Rails.application.routes.draw do

  get 'users/profile'

  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :comments

  resources :posts do

    resources :likes, only: [:create, :update]

    collection do
      get :technology
      get :health
      get :business
      get :outdoors
      get :home
      get :other
    end
  end

  resources :groups do
    resources :posts
  end

  get 'indexprivate/', to:'posts#indexprivate', as: 'private'
  get 'private_technology/', to:'posts#indexprivate_technology', as: 'private_tec'
  get 'private_health/', to:'posts#indexprivate_health', as: 'private_hea'
  get 'private_business/', to:'posts#indexprivate_business', as: 'private_bus'
  get 'private_outdoors/', to:'posts#indexprivate_outdoors', as: 'private_out'
  get 'private_home/', to:'posts#indexprivate_home', as: 'private_hom'
  get 'private_other/', to:'posts#indexprivate_other', as: 'private_oth'

  get 'landing/index'

  root 'posts#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_users
  has_many :users, through: :group_users
  belongs_to :user
  has_many :posts
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :set_group, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /groups
  # GET /groups.json
  def index

    @groups = User.all
    @group = Group.new
    @available_groups = User.find(current_user.id).groups
    # @not_accepted = User.joins(:group_user).where(accepted:false)
    # @group_post = Post.joins(user: :group).where(group_id: current_user.groups.first)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group_posts = @group.posts.all

  end

  def decision
    @groupUser = GroupUser.where(group_id: params[:id], user_id: params[:user_id])
    if params[:decision] == "true"
      @groupUser.update(accepted: true)
    else
      @groupUser.update(accepted: false)
    end
    redirect_to groups_path
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
        format.js
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, remote:true) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<% unless group.id.nil? %>

<div id="group-<%=group.id%>" class="">

  <div  id="group_card" class="card grey darken-3  z-depth-3 ">
    <div id="group_row" class="row">
      <div class="card-title white-text">
        <h4 id="group_name"  class=" z-depth-3  grey"><%= group.name %></h4>
      </div>
      <div id="" class="card-content white-text col s12 m12 l9">
        <p class="group_description"><strong>Description:</strong></p>
        <p class="group_description_text"><%= group.description %></p><br>
        <p><strong>Created:</strong> <%= group.created_at.strftime('%F') %> </p>
        <% unless group.id.nil? %>
        <p><strong>Created by:</strong> <%= group.user.username %> </p>
        <% end %>
      </div>
      <div class="col s12 m12 l3">

      </div>
    </div>

    <div id="action-sec" class="row z-depth-2 toc-wrapper row">
      <!-- <div class="row"> -->
        <div class="col s8 m8 l8 blue  waves-light waves-effect">
          <!-- <p class="center-align">ENTER</p> -->
          <p><%= link_to 'OPEN GROUP', group, class:"white-text center-align" %></p>
        </div>
        <div class="col s4 m4 l4 red waves-light  waves-effect">
          <p class="center-align">ABANDON</p>

        </div>
      <!-- </div> -->
    </div>

  </div>

</div>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index(copy invites).html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<%= render 'form' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.user %></td>
        <td><%= group.description %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="group-invites" class="">
  <% @not_accepted.each do |n|%>
    <div class="invite">
      <div class="">
        <p><%= "#{n.user.name} has invited you to join" %></p>
      </div>
      <h4><%= n.name  %></h4>
      <br>
      <p><%= n.description %></p>
    </div>
    <%= link_to 'Accept', {:controller => "group",
                                   :action => "decision",
                                   :id => n.group_id,
                                   :user_id => n.user.id,
                                   :decision => "true"}, method: 'post', class: "btn btn-sm btn-success" %>

    <%= link_to 'Reject', {:controller => "group",
                                  :action => "decision",
                                  :id => n.group_id,
                                  :user_id => n.user.id,
                                  :decision => "true"}, method: 'post', class: "btn btn-sm btn-success" %>
  <% end %>
</div>





<%= link_to 'New Group', new_group_path %>

app/views/groups/index(pre materialize).html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<%= render 'form' %>

<div id="idea-area" class="container-fluid idea-container">
  <%= render @groups %>
</div>


<br>

</div>





<%= link_to 'New Group', new_group_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>


<section class="apart-size ">
  <div class="row">
    <div class="col z-depth-3 toc-wrapper hide-on-small-only s12 m6 l4">
      <div class="container-chan-left z-depth-3 pinned">
        <div id="group-form-area" class="container">
          <h4>Create a new group</h4>
          <%= render 'form' %>

        </div>
      </div>
    </div>
    <div class="col s12 m6 l8">
      <div class="container">
        <%= render @available_groups %>
      </div>
    </div>
  </div>


</section>
<br>

</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

  <ul id="slide-out" class="apart side-nav fixed z-depth-4 ">
    <li id="category-logo" class="red z-depth-5"><h3>Categories</h3></li>
    <li class="li-a-color-a " ><a href="#">All</a></li>
    <li class="li-a-color-t " ><a href="#">Technology</a></li>
    <li class="li-a-color-he" ><a href="#">Health</a></li>
    <li class="li-a-color-b " ><a href="#">Business</a></li>
    <li class="li-a-color-ou " ><a href="#">Outdoors</a></li>
    <li class="li-a-color-ho" ><a href="#">Home</a></li>
    <li class="li-a-color-ot " ><a href="#">Other</a></li>

  </ul>
  <!-- <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a> -->
<main class="apart ">
  <div id="main-box" class="row">

    <div id="post-bar" class="z-depth-0">
      <div id="idea-area" class="">

        <%= render @group_posts %>

      </div>
    </div>
  </div>
</main>

<script>
  $(document).ready(function () {
    document.elementFromPoint(550, 200).click();
  });
</script>