config/routes.rb
Rails.application.routes.draw do

  get 'users/profile'

  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :comments

  resources :posts do

    resources :likes, only: [:create, :update]

    collection do
      get :technology
      get :health
      get :business
      get :outdoors
      get :home
      get :other
    end
  end

  resources :groups do
    resources :posts
  end

  get 'indexprivate/', to:'posts#indexprivate', as: 'private'
  get 'private_technology/', to:'posts#indexprivate_technology', as: 'private_tec'
  get 'private_health/', to:'posts#indexprivate_health', as: 'private_hea'
  get 'private_business/', to:'posts#indexprivate_business', as: 'private_bus'
  get 'private_outdoors/', to:'posts#indexprivate_outdoors', as: 'private_out'
  get 'private_home/', to:'posts#indexprivate_home', as: 'private_hom'
  get 'private_other/', to:'posts#indexprivate_other', as: 'private_oth'

  get 'landing/index'

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  # belongs_to :category
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  belongs_to :group
  has_many :comments
  has_many :likes

  validates :category, presence: true
  validates :title, presence: true

  validates :content, presence: true

  scope :technology,    ->{ where( category:"Technology")}
  scope :health,        ->{ where( category:"Health")}
  scope :business,      ->{  where(category:"Business")}
  scope :outdoors,      ->{ where( category:"Outdoors")}
  scope :home,          ->{ where( category:"Home")}
  scope :other,         ->{  where(category:"Other")}

  scope :technology_private,    ->{ where( category:"Technology")}
  scope :health_private,        ->{ where( category:"Health")}
  scope :business_private,      ->{  where(category:"Business")}
  scope :outdoors_private,      ->{ where( category:"Outdoors")}
  scope :home_private,          ->{ where( category:"Home")}
  scope :other_private,         ->{  where( category:"Other")}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource


  # GET /posts
  # GET /posts.json
  def index
    if params[:filter].blank?
      @posts = Post.all.order("created_at DESC")
      @posts_explore = Post.all.where(public: true ).order("created_at DESC")
    else
      @posts = Post.where("title like ?", "%#{params[:filter]}%")
      @posts_explore = Post.all.where(public: true ).where("title like ?", "%#{params[:filter]}%").order("created_at DESC")

    end
    # @posts_private = Post.where(user_id: :current_user.id )
    @post = Post.new

  end

  def technology
    @posts_explore = Post.technology.order("created_at DESC").where(public: true )
    render action: :index
  end
  def health
    @posts_explore = Post.health.order("created_at DESC").where(public: true )
    render action: :index
  end
  def business
    @posts_explore = Post.business.order("created_at DESC").where(public: true )
    render action: :index
  end
  def outdoors
    @posts_explore = Post.outdoors.order("created_at DESC").where(public: true )
    render action: :index
  end
  def home
    @posts_explore = Post.home.order("created_at DESC").where(public: true )
    render action: :index
  end
  def other
    @posts_explore = Post.other.order("created_at DESC").where(public: true )
    render action: :index
  end


# for indexprivate
  def indexprivate_technology
    @posts_private = Post.technology_private.order("created_at DESC")
    render action: :indexprivate
  end
  def indexprivate_health
    @posts_private = Post.health_private.order("created_at DESC")
    render action: :indexprivate
  end
  def indexprivate_business
    @posts_privateprivate = Post.business_private.order("created_at DESC")
    render action: :indexprivate
  end
  def indexprivate_outdoors
    @posts_private = Post.outdoors_private.order("created_at DESC")
    render action: :indexprivate
  end
  def indexprivate_home
    @posts_private = Post.home_private.order("created_at DESC")
    render action: :indexprivate
  end
  def indexprivate_other
    @posts_private = Post.other_private.order("created_at DESC")
    render action: :indexprivate
  end





  def indexprivate
    # @posts = Post.all
    @posts_private = Post.all.where(user_id: current_user.id ).order("created_at DESC")
    #code
    if params[:filter].blank?
      # @posts = Post.all.order("created_at DESC")
      @posts_private = Post.all.where(user_id: current_user.id ).order("created_at DESC")
    else
      # @posts = Post.where("title like ?", "%#{params[:filter]}%")
      @posts_private = Post.all.where(user_id: current_user.id ).where("title like ?", "%#{params[:filter]}%").order("created_at DESC")

    end
    # @posts_private = Post.where(user_id: :current_user.id )
    @post = Post.new

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = @post.comments.new
    # if @comments == []
    #   @comments = @post.comments.new
    # end
  end

  # GET /posts/new
  def new
    @post = Post.new
    # @current_group = params[:group_id]
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        flash[:alert] = @post.errors.full_messages
        @post = Post.new(post_params)
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :photo, :photo_cache,:remote_photo_url, :content, :category, :user_id, :likecount, :dislikecount, :reportcount, :commentcount, :public, :group_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form(copy pre-edit).html.erb
<%= form_for(@post, remote:true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html(copy).erb
<%= form_for(@post, remote:true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <!-- <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :likecount %><br>
    <%= f.number_field :likecount %>
  </div>
  <div class="field">
    <%= f.label :dislikecount %><br>
    <%= f.number_field :dislikecount %>
  </div>
  <div class="field">
    <%= f.label :reportcount %><br>
    <%= f.number_field :reportcount %>
  </div>
  <div class="field">
    <%= f.label :commentcount %><br>
    <%= f.number_field :commentcount %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post, remote:false, html:{ multipart:true}) do |f| %>


  <div id="post-form-box" class="apart-2 container ">

    <div class="row apart">
      <div class="col s12 m8 l8">
        <div class="error-area container z-depth-2 red lighten-2">
          <% if @post.errors.any? %>
          <div id="error_explanation">
            <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

            <ul>
              <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
        </div>
        <h4>Describe your idea</h4>
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: "z-depth-1 shadow_override" %>
        </div>
        <div class="field">
          <%= f.label :content %><br>
          <%= f.text_area :content, class:"z-depth-1 borderless_box form_text" %>
        </div>

        <div>
          <%= f.submit "STASH IDEA", class:"btn green actions", id:"form_submit" %>
          <%= f.submit "clear", :type => "reset", class:"btn red actions" %>
          <%= link_to 'CANCEL', posts_path, class:"btn grey actions" %>
        </div>

      </div>
      <div class="side-form col s12 m4 l4 z-depth-2">
        <div class="field  side-form-pads  ">
          <%= f.label :category %><br>


            <p>
              <%= f.radio_button(:category, "Technology") %>
              <%= f.label(:category, "Technology", value: "Technology") %>
            </p>
            <p>
              <%= f.radio_button(:category, "Health") %>
              <%= f.label(:category, "Health", value: "Health") %>
            </p>
            <p>
              <%= f.radio_button(:category, "Business") %>
              <%= f.label(:category, "Business", value: "Business") %>
            </p>
            <p>
              <%= f.radio_button(:category, "Outdoors") %>
              <%= f.label(:category, "Outdoors", value: "Outdoors") %>
            </p>
            <p>
              <%= f.radio_button(:category, "Home") %>
              <%= f.label(:category, "Home", value: "Home") %>
            </p>
            <p>
              <%= f.radio_button(:category, "Other") %>
              <%= f.label(:category, "Other", value: "Other") %>
            </p>


        </div>
        <br>

        <div class="file-field   side-form-pads">
          <div class="">
            <%= f.label :picture %>
          </div>
          <div class="btn teal">
            <span>File</span>
            <%= f.file_field :photo, class:"file-path" %>
          </div>
          <div class="file-path-wrapper">
          </div>
          <%= f.hidden_field :photo_cache %>
        </div>

        <div class=" side-form-pads ">
          <div class="field ">
            <%= f.label :picture_from_web %><br>
            <%= f.text_field :remote_photo_url %>
          </div>
        </div>

        <div class="field hide">
          <%= f.label :user_id %><br>
          <%= f.text_field :user_id, value:current_user.id %>
        </div>
        <div class="field hide">
          <%= f.label :group_id %><br>
          <%= f.text_field :group_id, value:params[:group_id] %>
        </div>

        <div class=" side-form-pads field">
          <%= f.label :privacy %><br>
          <!-- <div class=""> -->
              <%= f.check_box :public, checked: true , class:"red filled-in" %>
              <%= f.label 'public', id:'public'%>
          <!-- </div> -->
        </div>

      </div>
    </div>



  </div>
<% end %>

<script>

</script>

app/views/posts/_post(pre materialize).html.erb
<div id="post-<%=post.id%>" class="container idea-panel">
  <div class="idea-title col-xs-12">
    <h3><%= post.title %></h3>
  </div>
  <div class="idea-description col-xs-12">
    <p><%= post.content %></p>
  </div>

  <div class="idea-user col-xs-12">
    <% if post.user == nil %>
      <p>
        Post doesnt have a user
      </p>
    <% else %>
      <p><%= post.user.name %></p>
    <% end %>
  </div>
  <div class="idea-open col-xs-8">
    <p><%= link_to 'Expand', post, class: "idea-open" %></p>
  </div>
  <div class="idea-up col-xs-2">
    Up
  </div>
  <div class="idea-down col-xs-2">
    Down
  </div>
</div>

app/views/posts/_post.html.erb
<div id="post-<%=post.id%>" class="idea-pack">
  <div id="post-panel-<%=post.id%>" class="waves-effect toc-wrapper col s12 m6 l7 valign hoverable z-depth-2 idea-panel">
    <!-- <div id="container-chan-left" class=""> -->

      <div class="square-box z-depth-4">
        <%=  image_tag post.photo, class:"img-responsive" %>
      </div>
      <div class="">
        <h5 class="truncate" ><%= post.title %></h5>
      </div>
      <div class="idea-description">
        <p class="truncate" ><%= post.user.username %></p>
      </div>
    <!-- </div> -->
  </div>

  <div class="idea-hidden-pre toc-wrapper hide-on-small-only col s12 m6 l5">
    <div id="view-<%=post.id%>" class="container-chan idea-hidden pinned hide">
      <!-- <div id="post-view-bar" class=" z-depth-0"> -->

        <!-- <div class="toc-wrapper"> -->
          <div id="category-sec" class="z-depth-3">
            <h5><strong><%= post.category %></strong></h5>
          </div>

          <div id="data-sec" class="z-depth-1 row">
            <div class="col s6 m6 l6">
              <strong>Date: </strong><%= post.created_at.strftime('%F') %>
            </div>
            <div class="col s6 m6 l6">
              <strong>Post ID: </strong><%= post.id %>
            </div>
          </div>

          <div id="content-sec" class="z-depth-2 ">
            <h4><%= post.title %></h4>
            <p><%= post.user.username %></p>
            <p class=""><%= post.content %></p>
          </div>

          <div id="action-sec" class="valign-wrapper row z-depth-2 ">
            <div id="post-add-<%=post.id%>" class="col s4 m4 l4 blue  waves-light waves-effect">
              <p class="center-align valign">ADD</p>
            </div>
            <div id="post-like-<%=post.id%>" class="col s4 m4 l4 green waves-light  waves-effect">
              <p class="center-align valign">LIKE</p>
            </div>
            <div id="post-dislike-<%=post.id%>" class="col s4 m4 l4 red waves-light waves-effect">
            <p class="center-align valign">DISLIKE</p>
            </div>
          </div>

          <div id="see-more" class=" z-depth-2  row">
            <div class=" valign-wrapper hoverable teal waves-effect col s12 m12 l12">
              <!-- <p class="">SEE MORE</p> -->
              <p><%= link_to 'SEE MORE', post, class:"center-align valign" %></p>

            </div>
          </div>
        <!-- </div> -->

      <!-- </div> -->
    </div>
  </div>

</div>
<script>
  $('#post-panel-<%=post.id%>').on('click', function(){
    $('.container-chan').addClass('hide');
    $('#view-<%=post.id%>').removeClass('hide');
    return false
  });

  $('#post-like-<%=post.id%>').on('click', function () {
    console.log('valor');
    $.ajax({
      type: "POST",
      url:'<%= post_likes_url(post) %>',
      dataType:'script'
    });
  });

</script>

app/views/posts/create.js.erb
$("#idea-area").append('<%= j render @post %>');

app/views/posts/index(2nd copy).html.erb
<p id="notice"><%= notice %></p>

<h1>Explore the public stash</h1>


<br>
<%= render 'form' %>

<input type="text" name="buscador"></input>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>

      <th>Likecount</th>
      <th>Dislikecount</th>
      <th>Reportcount</th>

    </tr>
  </thead>

  <tbody>
    <%= render @posts %>
  </tbody>

</table>

<script>

  $(document).ready(function(){

    $("[name='buscador']").on("input", function(){
      // console.log("hola");
      // console.log($(this).val());

      var filter = $(this).val();
      $.ajax({
        url: '<%= posts_path %>',
        type: 'GET',
        dataType: 'script',
        data: { filter: filter }
      })

    });

  });

</script>

app/views/posts/index(3rd bootrtraplesscopy).html.erb
<p id="notice"><%= notice %></p>

<% if current_user.nil? %>
  <a href="<%= new_user_registration_path %> ">
    <div id="add-idea" class="">
      <h2>Add your own idea</h2>
    </div>
  </a>
<% else %>
  <div id="add-idea" class="">
    <h2>Add your own idea</h2>
  </div>
<% end %>

<%= render 'form' %>

<div id="idea-area" class="container-fluid idea-container">
  <%= render @posts %>
</div>


<script>

    $(document).ready(function(){
      // $("#add-idea").css("box-shadow"," 0px 2px -10px 10px rgb(0, 0, 0)")

      var toggle_form = 0
      $("#add-idea").on({
        mouseenter: function() {
          $(this).css("background-color", "rgb(232, 255, 212)");
          $(this).css("box-shadow","0px 2px 20px 2px rgb(0, 0, 0)");
          // $("#add-idea h3").css("color", "rgb(255, 255, 255)");
          $(this).animate({
            // height: "60px",
            // opacity: 0.8,
          },200).css("color", "black");

          $("#idea-area").animate({
            opacity: 0.4
          },300).css("color", "black");

        },
        mouseleave: function () {
          $(this).css("background-color","rgb(255, 255, 255)");
          $(this).css("box-shadow","0px 2px 10px -2px rgb(0, 0, 0)");
          // $("#add-idea h3").css("color", "rgb(0, 0, 0)");
          $(this).animate({
            // height: "50px",
            // opacity: 1
          },200).css("color", "black");

          $("#idea-area").animate({
            opacity: 1
          },200).css("color", "black");
        },
        click: function () {
          if (toggle_form == 0) {
            $('#post-form-box').removeClass("hidden");
            toggle_form = 1
          } else {
            $('#post-form-box').addClass("hidden");
            toggle_form = 0
          };
        }
      });
      // $('#form_submit').on('click', function () {
      //   $('.grid').masonry({
      //     // options
      //     itemSelector: '.grid-item',
      //     columnWidth: 200
      //   });
      // });
      // $('.grid').masonry({
      //   // options
      //   itemSelector: '.grid-item',
      //   columnWidth: 200
      // });

              // Masonry
    //   $('.append-button').on( 'click', function() {
    //     // create new item elements
    //     var $items = $('<div class="grid-item">...</div>');
    //     // append items to grid
    //     $grid.append( $items )
    //     // add and lay out newly appended items
    //     .masonry( 'appended', $items );
    //   });
    });
</script>

app/views/posts/index(copy).html.erb
<p id="notice"><%= notice %></p>

<h1>Explore the public stash</h1>


<br>
<%= render 'form' %>
<%= link_to 'New Post', new_post_path %>




<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <!-- <th>Category</th> -->
      <th>User</th>
      <th>Likecount</th>
      <th>Dislikecount</th>
      <th>Reportcount</th>
      <th>Commentcount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>

        <td><%= post.user %></td>
        <td><%= post.likecount %></td>
        <td><%= post.dislikecount %></td>
        <td><%= post.reportcount %></td>
        <td><%= post.commentcount %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/index(pre reformat).html.erb
<p id="notice"><%= notice %></p>

  <ul id="slide-out" class="apart side-nav fixed z-depth-3 ">
    <li></li>
    <li class="z-depth-2"><h3>Categories</h3></li>
    <li><a href="#!">All</a></li>
    <li><a href="#!">Technology</a></li>
    <li><a href="#!">Health</a></li>
    <li><a href="#!">Business</a></li>
    <li><a href="#!">Outdoors</a></li>
    <li><a href="#!">Home</a></li>
    <li><a href="#!">Other</a></li>

  </ul>
  <!-- <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a> -->
<main class="apart ">
  <div id="main-box" class="row">

    <div id="post-bar" class="z-depth-1 col s12 m6 l7">
      <div id="idea-area" class="container-fluid idea-container">
        <%= render @posts %>
      </div>
    </div>


    <div id="post-view-bar" class="pinned hide-on-small-only lime lighten-4 z-depth-3 col s12 m6 l4">
      view
    </div>


  </div>
</main>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

  <ul id="slide-out" class="apart side-nav fixed z-depth-4 ">
    <li id="category-logo" class="orange darken-4 z-depth-5"><h3>Categories</h3></li>
    <li><input type="text" name="buscador" value="" placeholder="  Search"></li>
    <li class="li-a-color-a " ><%= link_to 'All', posts_path %></li>
    <li class="li-a-color-t " ><%= link_to 'Technology', technology_posts_path %></li>
    <li class="li-a-color-he" ><%= link_to 'Health', health_posts_path %></li>
    <li class="li-a-color-b " ><%= link_to 'Business', business_posts_path %></li>
    <li class="li-a-color-ou " ><%= link_to 'Outdoors', outdoors_posts_path %></li>
    <li class="li-a-color-ho" ><%= link_to 'Home', home_posts_path %></li>
    <li class="li-a-color-ot " ><%= link_to 'Other', other_posts_path %></li>
    <% unless current_user.nil? %>
    <li><%= link_to 'New post', new_post_path %></li>
    <% end %>
  </ul>
  <!-- <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a> -->
<main class="apart ">
  <div id="main-box" class="row">

    <div id="post-bar" class="z-depth-0">
      <div id="idea-area" class="">

        <%= render @posts_explore %>

      </div>
    </div>
  </div>
</main>

<%= link_to 'New post', new_post_path %>



<script>
  $(document).ready(function () {
    document.elementFromPoint(550, 200).click();

      $("[name = 'buscador']").on('input', function(){
       var filter = $(this).val();
       $.ajax({
         url:'<%= posts_path %>',
         type:'GET',
         dataType: 'script',
         data: {filter: filter}
       });
     });
     //
    //  $('.idea-pack').click(function() {
    //    $(this).removeClass('hide');
    //  });
  });
</script>

app/views/posts/indexprivate.html.erb
private_<p id="notice"><%= notice %></p>

  <ul id="slide-out" class="apart side-nav fixed z-depth-3 ">
    <li id="category-logo" class="red z-depth-4"><h3>Categories</h3></li>

    <li><input type="text" name="buscador" value=""></li>
    <li class="li-a-color-a " ><%= link_to 'All', private_path %></li>

    <li class="" ><a href="#">Your ideas</a></li>
    <li class="" ><a href="#">Added ideas</a></li>
    <li class="li-a-color-t " ><%= link_to 'Technology', private_tec_path %></li>
    <li class="li-a-color-he" ><%= link_to 'Health', private_hea_path %></li>
    <li class="li-a-color-b " ><%= link_to 'Business', private_bus_path %></li>
    <li class="li-a-color-ou " ><%= link_to 'Outdoors', private_out_path %></li>
    <li class="li-a-color-ho" ><%= link_to 'Home', private_hom_path %></li>
    <li class="li-a-color-ot " ><%= link_to 'Other', private_oth_path %></li>
    <li><%= link_to 'New post', new_post_path %></li>
  </ul>
  <!-- <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a> -->
<main class="apart ">
  <div id="main-box" class="row">

    <div id="post-bar" class="z-depth-0">
      <div id="idea-area" class="">

        <%= render @posts_private %>

      </div>
    </div>

  </div>
</main>


<script>
  $(document).ready(function () {
      document.elementFromPoint(550, 200).click();

      $("[name = 'buscador']").on('input', function(){
       var filter = $(this).val();
       $.ajax({
         url:'<%= posts_path %>',
         type:'GET',
         dataType: 'script',
         data: {filter: filter}
       });
     });
  });
</script>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show(copy).html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Likecount:</strong>
  <%= @post.likecount %>
</p>

<p>
  <strong>Dislikecount:</strong>
  <%= @post.dislikecount %>
</p>

<p>
  <strong>Reportcount:</strong>
  <%= @post.reportcount %>
</p>

<p>
  <strong>Commentcount:</strong>
  <%= @post.commentcount %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>